/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.h4h.fhir

import io.h4h.fhir.r4.resources.Questionnaire
import kotlin.test.Test


class QuestionnaireTest : SerializerTest() {


    @Test fun deserializeSerializeQuestionnaire1() =
        kotlinxDeserializeSerializeResource<Questionnaire>("questionnaire1.json")

    @Test fun deserializeSerializeQuestionnaire2() =
        kotlinxDeserializeSerializeResource<Questionnaire>("questionnaire2.json")


}
